[package]
name = "images-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rocket = "=0.5.0-rc.3"
sqlx = "0.7.1"
nanoid = "0.4.0"

[dependencies.rocket_db_pools]
version = "=0.1.0-rc.3"
features = ["sqlx_postgres"]
